# Generated by Django 4.2 on 2024-02-01 00:15

import ckeditor_uploader.fields
import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('url_hash', models.SlugField(default='89453', help_text='Unique URL path for the Article', max_length=5, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default='', help_text='Title of the Article', max_length=1000)),
                ('description', models.TextField(default='', max_length=1000)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('image_alt', models.CharField(default='', max_length=100)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('is_featured', models.BooleanField(default=False, help_text='Featured Article? (Will display as first Article on Homepage)')),
                ('published_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'ordering': ('title', 'published_at', 'url_hash'),
            },
        ),
    ]
