# Generated by Django 4.2 on 2025-01-22 16:37

import app.models
import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_name', models.CharField(default='', max_length=50)),
                ('tag_hash', models.CharField(default=app.models.hash_generate, max_length=5, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ('tag_name', 'tag_hash'),
            },
        ),
        migrations.CreateModel(
            name='WebsiteDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', max_length=9000)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Website Description',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('url_hash', models.SlugField(default=app.models.random_digits, help_text='Unique URL path for the Article', max_length=5, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default='', help_text='Title of the Article', max_length=1000)),
                ('description', models.TextField(default='', max_length=1000)),
                ('image', models.ImageField(default='', upload_to='assets/article')),
                ('image_alt', models.CharField(default='', max_length=100)),
                ('content', ckeditor.fields.RichTextField()),
                ('is_featured', models.BooleanField(default=False, help_text='Featured Article? (Will display as first Article on Homepage)')),
                ('published_at', models.DateTimeField(default=datetime.datetime.now)),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tag')),
            ],
            options={
                'ordering': ('title', 'published_at', 'url_hash'),
            },
        ),
    ]
