# Generated by Django 4.2 on 2024-02-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url_hash',
            field=models.SlugField(default='67838', help_text='Unique URL path for the Article', max_length=5, primary_key=True, serialize=False, unique=True),
        ),
    ]
