# Generated by Django 4.2 on 2025-03-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ("title", "published_at", "url_hash"),
                "verbose_name_plural": "Articles",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ("tag_name", "tag_hash"),
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.AlterField(
            model_name="article",
            name="description",
            field=models.TextField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="article",
            name="image_alt",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="article",
            name="url_hash",
            field=models.SlugField(
                blank=True,
                default="",
                help_text="Unique URL path for the Article",
                max_length=5,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="tag_hash",
            field=models.CharField(
                blank=True,
                default="",
                max_length=5,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
