# Generated by Django 4.2 on 2024-02-20 00:24

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_name', models.CharField(default='', max_length=50)),
                ('tag_hash', models.CharField(default=app.models.hash_generate, max_length=5, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ('tag_name', 'tag_hash'),
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='url_hash',
            field=models.SlugField(default=app.models.random_digits, help_text='Unique URL path for the Article', max_length=5, primary_key=True, serialize=False, unique=True),
        ),
    ]
