# Generated by Django 4.2 on 2025-03-08 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_article_options_alter_tag_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image_url",
            field=models.URLField(blank=True, default="", max_length=1000),
        ),
    ]
