# Generated by Django 5.2.1 on 2025-05-16 12:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_article_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Content of the Article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Description of the Article. Autogenerated (via Gemini AI) if not provided', max_length=1000),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='', help_text='Image field for use in Development Environment', upload_to='assets/article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_alt',
            field=models.CharField(blank=True, default='', help_text='Image Alternative Text (autogenerating from image if not provided). Autogeneration is done using AI', max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='Image URL field for use in Production Environment', max_length=1000),
        ),
    ]
