# Generated by Django 4.2 on 2024-02-01 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_article_image_alter_article_url_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url_hash',
            field=models.SlugField(default='27827', help_text='Unique URL path for the Article', max_length=5, primary_key=True, serialize=False, unique=True),
        ),
    ]
