# Generated by Django 4.2 on 2025-01-21 13:15

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('certification_hash', models.CharField(default=app.models.hash_generate, max_length=3, primary_key=True, serialize=False)),
                ('institution', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('degree', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('certification_id', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('certification_url', models.URLField(blank=True, default='', null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('degree', 'institution', 'start_date', 'end_date', 'is_published'),
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('experience_id', models.CharField(default=app.models.random_digits, max_length=5, primary_key=True, serialize=False)),
                ('company', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('position', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('company', 'start_date', 'end_date', 'is_published'),
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_hash', models.CharField(default=app.models.hash_generate, max_length=3, primary_key=True, serialize=False)),
                ('organization_name', models.CharField(default='', max_length=1000)),
                ('organization_logo', models.ImageField(default='', upload_to='assets/organization')),
                ('organization_logo_alt', models.CharField(default='', max_length=1000)),
            ],
            options={
                'ordering': ('organization_name', 'organization_hash'),
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.CharField(default=app.models.random_digits, max_length=5, primary_key=True, serialize=False)),
                ('skill_name', models.CharField(default='', max_length=1000)),
            ],
            options={
                'ordering': ('skill_name', 'skill_id'),
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_summary', models.TextField(blank=True, default='', null=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
