# Generated by Django 4.2 on 2025-03-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certification",
            name="certification_hash",
            field=models.CharField(
                blank=True, default="", max_length=3, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="experience",
            name="experience_id",
            field=models.CharField(
                blank=True, default="", max_length=5, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="organization_hash",
            field=models.CharField(
                blank=True, default="", max_length=3, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="organization_logo_alt",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="skill",
            name="skill_id",
            field=models.CharField(
                blank=True, default="", max_length=5, primary_key=True, serialize=False
            ),
        ),
    ]
