# Generated by Django 4.2 on 2025-01-21 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_summary_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ('degree', 'institution', 'start_date', 'end_date', 'is_published', 'certification_hash')},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ('company', 'start_date', 'end_date', 'is_published', 'experience_id')},
        ),
    ]
